spring.application.name=apppais

server.port = 6767

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://mysqldes3.gpcueb.org:3306/estudiante70

spring.datasource.username=estudiante70

spring.datasource.password=@L9CpG7etxkH

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver