spring.application.name=AppPaises

spring.jpa.hibernate.ddl-auto=update
#me permite indicarle al spring la sentencia de la base de datos

spring.datasource.url=jdbc:mysql://mysqldes3.gpcueb.org:3306/estudiante69
#aqui se coloca la ubicacion de la base de datos a utilizar

spring.datasource.username=estudiante69
#se utiliza para colocar el nombre de usuario para poder acceder la base de datos 

spring.datasource.password=hgqPu2*b4NtH
#se utiliza para colocar la contraseña min 12 caracteres 1 mayus 1 simbolo 1min 1num

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
